version: "3.2"

services:
     elasticsearch:
          image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
          container_name: elasticsearch
          hostname: elasticsearch
#          volumes:
#               - ./data/elasticsearch:/usr/share/elasticsearch/data
          environment:
               ES_JAVA_OPTS: "-Xmx256m -Xms256m"
               ELASTIC_PASSWORD: "root"
               xpack.security.enabled: "true"
               xpack.monitoring.collection.enabled: "true"
               discovery.type: "single-node"
          ports:
               - "9200:9200"
               - "9300:9300"
          networks:
               - elastic
     kibana:
          image: docker.elastic.co/kibana/kibana:7.15.0
          container_name: kibana
          hostname: kibana
          volumes:
               - ./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:rw
          ports:
               - "5601:5601"
          links:
               - elasticsearch:elasticsearch
          depends_on:
               - elasticsearch
          networks:
               - elastic
     logstash:
          image: docker.elastic.co/logstash/logstash:7.15.0
          container_name: logstash
          hostname: logstash
          ports:
               - "5044:5044"
               - "9600:9600"
          command: logstash -f /usr/share/logstash/pipeline/logstash.conf
          volumes:
               - ./config/logstash:/usr/share/logstash/pipeline/
          links:
               - elasticsearch:elasticsearch
          depends_on:
               - elasticsearch
          networks:
               - elastic
     app:
          container_name: app
          build: .
          restart: on-failure
          command:
               - ./run.sh
          ports:
               - "8080:8080"
          volumes:
               - ./data/cv:/root/.m2
          depends_on:
               - elasticsearch
               - logstash
          networks:
               - elastic
     cvindexer:
          container_name: cvindexer
          build: ./cv-indexer
          restart: on-failure
          ports:
               - "80:5000"
          depends_on:
               - app
          networks:
               - elastic
networks:
     elastic:
          driver: bridge
