version: 2.1 # CircleCI version
jobs:
  unit-test:
    machine: true
    steps:
      - checkout
      - run: ./mvnw test -Dtest="CvUtilTest"
      - store_artifacts:
          path: store-results
  build-test:
    machine: true # Use a Linux VM instead of docker environment
    steps:
      - checkout
      - run: docker-compose up -d --build elasticsearch kibana logstash
      - run: docker-compose up -d --build app
      - run: docker-compose up -d --build cvindexer
      - run: docker exec -it app ./mvnw test
      - store_artifacts:
          path: ~/CVIndexing/features/fail-screenshots

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-test-deploy:
    jobs:
      - unit-test
      - build-test:
          requires:
            - unit-test
